[project]
name = "aphorism-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "prometheus-client>=0.21.1",
    "requests>=2.32.3",
]
